tests: added test to check for webpack stats
Signed-off-by: Trey <73353716+TreyWW@users.noreply.github.com>

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -71,6 +71,12 @@ jobs:
             echo "frontend/static/js/c/ was not created from webpack build"
             exit 1
           fi
+          if [ -f webpack-stats.json ]; then
+            echo "webpack has built webpack-stats to work with chunks"
+          else
+            echo "webpack-stats was not built so cannot work with chunks"
+            exit 1
+          fi
 
       #----------------------------------------------
       #       run docker compose & tests
